{
 "title": "Air Tracking",
 "description": "This Grafana dashboard provides temperature and humidity metrics using Prometheus, and is a reference sample for the sensor-data-monitoring-grafana project.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Technical Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime Sensor 1",
   "type": "stat",
   "description": "SENS01 Uptime",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_uptime_seconds{sensor=\"SENS01\"} / 86400\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signal Strength Sensor 1",
   "type": "stat",
   "description": "SENS01 WLAN Signal Strenght",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBM" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_wifi_rssi_dbm{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Poll Duration Sensor 1",
   "type": "stat",
   "description": "SENS01 Last Poll",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_exporter_poll_seconds{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Living Room Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_temperature_celsius{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_humidity_percent{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_pressure_hpa{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carbon Dioxide Value",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_eco2_ppm{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parts per Billion",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_tvoc_ppb{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Living Room Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "esp32_json_temperature_celsius{sensor=\"SENS01\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "esp32_json_humidity_percent{sensor=\"SENS01\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "esp32_json_pressure_hpa{sensor=\"SENS01\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carbon Dioxide Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "esp32_json_eco2_ppm{sensor=\"SENS01\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parts per Billion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "expr": "esp32_json_tvoc_ppb{sensor=\"SENS01\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}