{
 "title": "Air Tracking",
 "description": "This Grafana dashboard provides temperature and humidity metrics using Prometheus, and is a reference sample for the sensor-data-monitoring-grafana project.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Outdoor Air Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature MüMü",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "weather_temperature_celsius{location=\"Münchsmünster\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Humidity MüMü",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "weather_humidity_percent{location=\"Münchsmünster\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wind Chill MüMü",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "weather_apparent_temperature_celsius{location=\"Münchsmünster\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Precipitation MüMü",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "mm/h" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "weather_precipitation_mm{location=\"Münchsmünster\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wind Speed MüMü",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "weather_wind_speed_kmh{location=\"Münchsmünster\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Temperature Münchsmünster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "weather_temperature_celsius{location=\"Münchsmünster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Humidity Münchsmünster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "weather_humidity_percent{location=\"Münchsmünster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wind Chill Münchsmünster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "weather_apparent_temperature_celsius{location=\"Münchsmünster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Precipitation Münchsmünster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "mm/h" } },
     "targets": [
      {
       "expr": "weather_precipitation_mm{location=\"Münchsmünster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wind Speed Münchsmünster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 449 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "targets": [
      {
       "expr": "weather_wind_speed_kmh{location=\"Münchsmünster\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Current Data | Living Room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_temperature_celsius{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_humidity_percent{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_pressure_hpa{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO₂ Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_eco2_ppm{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VOC Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_tvoc_ppb{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current Data | Bathroom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_temperature_celsius{sensor=\"SENS02\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_humidity_percent{sensor=\"SENS02\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_pressure_hpa{sensor=\"SENS02\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO₂ Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_eco2_ppm{sensor=\"SENS02\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VOC Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_tvoc_ppb{sensor=\"SENS02\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current Data | Bedroom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_temperature_celsius{sensor=\"SENS03\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_humidity_percent{sensor=\"SENS03\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_pressure_hpa{sensor=\"SENS03\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO₂ Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_eco2_ppm{sensor=\"SENS03\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VOC Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp32_json_tvoc_ppb{sensor=\"SENS03\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Series | Living Room",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "esp32_json_temperature_celsius{sensor=\"SENS01\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "esp32_json_humidity_percent{sensor=\"SENS01\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Barometric Pressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "targets": [
      {
       "expr": "esp32_json_pressure_hpa{sensor=\"SENS01\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CO₂ Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "expr": "esp32_json_eco2_ppm{sensor=\"SENS01\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VOC Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "conppb" } },
     "targets": [
      {
       "expr": "esp32_json_tvoc_ppb{sensor=\"SENS01\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Time Series | Bathroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "esp32_json_temperature_celsius{sensor=\"SENS02\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "esp32_json_humidity_percent{sensor=\"SENS02\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Barometric Pressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "targets": [
      {
       "expr": "esp32_json_pressure_hpa{sensor=\"SENS02\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CO₂ Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "expr": "esp32_json_eco2_ppm{sensor=\"SENS02\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VOC Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "conppb" } },
     "targets": [
      {
       "expr": "esp32_json_tvoc_ppb{sensor=\"SENS02\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Time Series | Bedroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "esp32_json_temperature_celsius{sensor=\"SENS03\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "esp32_json_humidity_percent{sensor=\"SENS03\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Barometric Pressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "targets": [
      {
       "expr": "esp32_json_pressure_hpa{sensor=\"SENS03\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CO₂ Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "expr": "esp32_json_eco2_ppm{sensor=\"SENS03\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VOC Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "conppb" } },
     "targets": [
      {
       "expr": "esp32_json_tvoc_ppb{sensor=\"SENS03\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Technical Stats | Living Room",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Living Room Uptime",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_uptime_seconds{sensor=\"SENS01\"} / 86400\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Signal Strength",
     "type": "stat",
     "description": "Living Room WLAN Signal Strenght",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "dBM" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_wifi_rssi_dbm{sensor=\"SENS01\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Poll Duration",
     "type": "stat",
     "description": "Living Room Last Poll",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_json_exporter_poll_seconds{sensor=\"SENS01\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CO₂ Level Baseline",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "esp32_json_eco2_min_window{sensor=\"SENS01\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Saved Baseline",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "esp32_json_bl_saved{sensor=\"SENS01\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Internal calibration status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "esp32_json_bl_current_window{sensor=\"SENS01\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Technical Stats | Bathroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Bathroom Uptime",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_uptime_seconds{sensor=\"SENS02\"} / 86400",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Signal Strength",
     "type": "stat",
     "description": "Bathroom WLAN Signal Strenght",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "dBM" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_wifi_rssi_dbm{sensor=\"SENS02\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Poll Duration",
     "type": "stat",
     "description": "Bathroom Last Poll",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_json_exporter_poll_seconds{sensor=\"SENS02\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CO₂ Level Baseline",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "esp32_json_eco2_min_window{sensor=\"SENS02\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Saved Baseline",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "esp32_json_bl_saved{sensor=\"SENS02\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Internal calibration status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "esp32_json_bl_current_window{sensor=\"SENS02\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Technical Stats | Bedroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Bedroom Uptime",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_uptime_seconds{sensor=\"SENS03\"} / 86400",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Signal Strength",
     "type": "stat",
     "description": "Bedroom WLAN Signal Strenght",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "dBM" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_wifi_rssi_dbm{sensor=\"SENS03\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Poll Duration",
     "type": "stat",
     "description": "Bedroom Last Poll",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_json_exporter_poll_seconds{sensor=\"SENS03\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CO₂ Level Baseline",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "esp32_json_eco2_min_window{sensor=\"SENS03\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Saved Baseline",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "esp32_json_bl_saved{sensor=\"SENS03\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Internal calibration status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "esp32_json_bl_current_window{sensor=\"SENS03\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}