{
 "title": "Air Tracking",
 "description": "This Grafana dashboard provides temperature and humidity metrics using Prometheus, and is a reference sample for the sensor-data-monitoring-grafana project.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Current Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature Living Room",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_temperature_celsius{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity Living Room",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_humidity_percent{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barometric Pressure Living Room",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_pressure_hpa{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carbon Dioxide Value Living Room",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_eco2_ppm{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parts per Billion Living Room",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_tvoc_ppb{sensor=\"SENS01\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Bathroom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_temperature_celsius{sensor=\"SENS02\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity Bathroom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_humidity_percent{sensor=\"SENS02\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barometric Pressure Bathroom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_pressure_hpa{sensor=\"SENS02\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carbon Dioxide Value Bathroom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_eco2_ppm{sensor=\"SENS02\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parts per Billion Bathroom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_tvoc_ppb{sensor=\"SENS02\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Bedroom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_temperature_celsius{sensor=\"SENS03\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity Bedroom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_humidity_percent{sensor=\"SENS03\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barometric Pressure Bedroom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_pressure_hpa{sensor=\"SENS03\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carbon Dioxide Value Bedroom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_eco2_ppm{sensor=\"SENS03\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parts per Billion Bedroom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_json_tvoc_ppb{sensor=\"SENS03\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Series Living Room",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature Living Room",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "esp32_json_temperature_celsius{sensor=\"SENS01\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Humidity Living Room",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "esp32_json_humidity_percent{sensor=\"SENS01\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Barometric Pressure Living Room",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "targets": [
      {
       "expr": "esp32_json_pressure_hpa{sensor=\"SENS01\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Parts per Billion Living Room",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "conppb" } },
     "targets": [
      {
       "expr": "esp32_json_tvoc_ppb{sensor=\"SENS01\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Carbon Dioxide Value Living Room",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "expr": "esp32_json_eco2_ppm{sensor=\"SENS01\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Time Series Bathroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature Bathroom",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "esp32_json_temperature_celsius{sensor=\"SENS02\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Humidity Bathroom",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "esp32_json_humidity_percent{sensor=\"SENS02\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Barometric Pressure Bathroom",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "targets": [
      {
       "expr": "esp32_json_pressure_hpa{sensor=\"SENS02\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Parts per Billion Bathroom",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "conppb" } },
     "targets": [
      {
       "expr": "esp32_json_tvoc_ppb{sensor=\"SENS02\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Carbon Dioxide Value Bathroom",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "expr": "esp32_json_eco2_ppm{sensor=\"SENS02\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Time Series Bedroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature Bedroom",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "esp32_json_temperature_celsius{sensor=\"SENS03\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Humidity Bedroom",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "esp32_json_humidity_percent{sensor=\"SENS03\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Barometric Pressure Bedroom",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "targets": [
      {
       "expr": "esp32_json_pressure_hpa{sensor=\"SENS03\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Parts per Billion Bedroom",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "conppb" } },
     "targets": [
      {
       "expr": "esp32_json_tvoc_ppb{sensor=\"SENS03\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Carbon Dioxide Value Bedroom",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "expr": "esp32_json_eco2_ppm{sensor=\"SENS03\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Technical Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime Sensor 1",
     "type": "stat",
     "description": "SENS01 Uptime",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_uptime_seconds{sensor=\"SENS01\"} / 86400\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Signal Strength Sensor 1",
     "type": "stat",
     "description": "SENS01 WLAN Signal Strenght",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "dBM" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_wifi_rssi_dbm{sensor=\"SENS01\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Poll Duration Sensor 1",
     "type": "stat",
     "description": "SENS01 Last Poll",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_json_exporter_poll_seconds{sensor=\"SENS01\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime Sensor 2",
     "type": "stat",
     "description": "SENS02 Uptime",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_uptime_seconds{sensor=\"SENS02\"} / 86400",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Signal Strength Sensor 2",
     "type": "stat",
     "description": "SENS02 WLAN Signal Strenght",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "dBM" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_wifi_rssi_dbm{sensor=\"SENS02\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Poll Duration Sensor 2",
     "type": "stat",
     "description": "SENS02 Last Poll",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_json_exporter_poll_seconds{sensor=\"SENS02\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime Sensor 2",
     "type": "stat",
     "description": "SENS02 Uptime",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_uptime_seconds{sensor=\"SENS03\"} / 86400",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Signal Strength Sensor 3",
     "type": "stat",
     "description": "SENS03 WLAN Signal Strenght",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "dBM" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_wifi_rssi_dbm{sensor=\"SENS03\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Poll Duration Sensor 3",
     "type": "stat",
     "description": "SENS03 Last Poll",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esp32_json_exporter_poll_seconds{sensor=\"SENS03\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}